//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juicy_Swapper_v2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Epic Games\\Fortnite\\FortniteGame\\Content\\Paks")]
        public string pakPath {
            get {
                return ((string)(this["pakPath"]));
            }
            set {
                this["pakPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int pakCount {
            get {
                return ((int)(this["pakCount"]));
            }
            set {
                this["pakCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skinTabEnabled {
            get {
                return ((bool)(this["skinTabEnabled"]));
            }
            set {
                this["skinTabEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool miscTabEnabled {
            get {
                return ((bool)(this["miscTabEnabled"]));
            }
            set {
                this["miscTabEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool renegadeRaiderEnabled {
            get {
                return ((bool)(this["renegadeRaiderEnabled"]));
            }
            set {
                this["renegadeRaiderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool renegadeRaiderCEnabled {
            get {
                return ((bool)(this["renegadeRaiderCEnabled"]));
            }
            set {
                this["renegadeRaiderCEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skullTrooperEnabled {
            get {
                return ((bool)(this["skullTrooperEnabled"]));
            }
            set {
                this["skullTrooperEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ghoulTrooperEnabled {
            get {
                return ((bool)(this["ghoulTrooperEnabled"]));
            }
            set {
                this["ghoulTrooperEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool fallenLoveRangerEnabled {
            get {
                return ((bool)(this["fallenLoveRangerEnabled"]));
            }
            set {
                this["fallenLoveRangerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dummyEnabled {
            get {
                return ((bool)(this["dummyEnabled"]));
            }
            set {
                this["dummyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool galaxyEnabled {
            get {
                return ((bool)(this["galaxyEnabled"]));
            }
            set {
                this["galaxyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool galacticDiscEnabled {
            get {
                return ((bool)(this["galacticDiscEnabled"]));
            }
            set {
                this["galacticDiscEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool stellarAxeEnabled {
            get {
                return ((bool)(this["stellarAxeEnabled"]));
            }
            set {
                this["stellarAxeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool raidersRevengeEnabled {
            get {
                return ((bool)(this["raidersRevengeEnabled"]));
            }
            set {
                this["raidersRevengeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool merryMintAxeEnabled {
            get {
                return ((bool)(this["merryMintAxeEnabled"]));
            }
            set {
                this["merryMintAxeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bootstrapsEnabled {
            get {
                return ((bool)(this["bootstrapsEnabled"]));
            }
            set {
                this["bootstrapsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool driverEnabled {
            get {
                return ((bool)(this["driverEnabled"]));
            }
            set {
                this["driverEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool harleyHitterEnabled {
            get {
                return ((bool)(this["harleyHitterEnabled"]));
            }
            set {
                this["harleyHitterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool widowsBiteEnabled {
            get {
                return ((bool)(this["widowsBiteEnabled"]));
            }
            set {
                this["widowsBiteEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool candyAxeEnabled {
            get {
                return ((bool)(this["candyAxeEnabled"]));
            }
            set {
                this["candyAxeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool studdedAxeEnabled {
            get {
                return ((bool)(this["studdedAxeEnabled"]));
            }
            set {
                this["studdedAxeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axeOfChampionsEnabled {
            get {
                return ((bool)(this["axeOfChampionsEnabled"]));
            }
            set {
                this["axeOfChampionsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rainbowCloverEnabled {
            get {
                return ((bool)(this["rainbowCloverEnabled"]));
            }
            set {
                this["rainbowCloverEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goobaEnabled {
            get {
                return ((bool)(this["goobaEnabled"]));
            }
            set {
                this["goobaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goosebumpsEnabled {
            get {
                return ((bool)(this["goosebumpsEnabled"]));
            }
            set {
                this["goosebumpsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sickoModeEnabled {
            get {
                return ((bool)(this["sickoModeEnabled"]));
            }
            set {
                this["sickoModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool stargazingEnabled {
            get {
                return ((bool)(this["stargazingEnabled"]));
            }
            set {
                this["stargazingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool moneyMachineEnabled {
            get {
                return ((bool)(this["moneyMachineEnabled"]));
            }
            set {
                this["moneyMachineEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool aerialAssaultOneEnabled {
            get {
                return ((bool)(this["aerialAssaultOneEnabled"]));
            }
            set {
                this["aerialAssaultOneEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cloudStrikeEnabled {
            get {
                return ((bool)(this["cloudStrikeEnabled"]));
            }
            set {
                this["cloudStrikeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool discoveryEnabled {
            get {
                return ((bool)(this["discoveryEnabled"]));
            }
            set {
                this["discoveryEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool getDownEnabled {
            get {
                return ((bool)(this["getDownEnabled"]));
            }
            set {
                this["getDownEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goldUmbrellaEnabled {
            get {
                return ((bool)(this["goldUmbrellaEnabled"]));
            }
            set {
                this["goldUmbrellaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool makoEnabled {
            get {
                return ((bool)(this["makoEnabled"]));
            }
            set {
                this["makoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool snowflakeEnabled {
            get {
                return ((bool)(this["snowflakeEnabled"]));
            }
            set {
                this["snowflakeEnabled"] = value;
            }
        }
    }
}
